### ISSUE TITLE
I tried it with PlatformIO and get undefined reference to `WinMain@16'

### ISSUE THREAD

**Issue by ats3788** [FabioBatSilva/ArduinoFake#16]
Where has the main.cpp File to be
I put it in the src folder.

**Comment by ats3788** [comment]
It does not work in my case with the Arduino syntax setup() & loop() you have to change it to main() function.

**Comment by trullock** [comment]
I have this exact issue, what is the solution @ats3788 

Thanks

**Comment by maxgerhardt** [comment]
When compiling for `platform = native` you need to define the `main()` function to generate a proper executable. The entry point of a normal PC program is not `setup()`. See [official example](https://github.com/platformio/platformio-examples/blob/develop/unit-testing/calculator/test/test_common/test_calculator.cpp#L55-L80) for a way to automatically create the correct entry point.

**Comment by prof7bit** [comment]
The examples here in this repository all have setup() and loop() and NO main(), so are these examples wrong?

**Comment by maxgerhardt** [comment]
Huh? 

Both of the examples here have the main function. It's intended for testing (`pio test`, sources in `test/`), not compilation of the `src/` program on the native platform. If you want that, you need a `main()`. 

https://github.com/FabioBatSilva/ArduinoFake/blob/910fc5f7dbbdc9d9094aadd29e108bcea063c540/examples/wiring-blink/test/test_main.cpp#L32-L42

https://github.com/FabioBatSilva/ArduinoFake/blob/910fc5f7dbbdc9d9094aadd29e108bcea063c540/examples/mock-injection/test/test_my_service.cpp#L40-L47

So that's alright.

**Comment by prof7bit** [comment]
https://github.com/FabioBatSilva/ArduinoFake/blob/master/examples/wiring-blink/src/main.cpp

**Comment by maxgerhardt** [comment]
You're pointing at a source in `src/`. This library is intended for testing, the sources in `test/` matter. `src/` is *supposed to be* your embedded firmare, `test/` the tests for your native machine.

**Comment by FabioBatSilva** [comment]
Thanks for the clarification @maxgerhardt 

@prof7bit , @ats3788 let me know if it still not clear..
